FROM node:18.20.8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .
COPY .env .env

EXPOSE 3000

CMD [ "npm", "start" ]
